name: Bug Report 🐞
description: Report a bug found in the project.
title: "[BUG] : "

body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description 🐞
      description: Enter a detailed description of the bug you encountered.
      placeholder: Please provide a detailed summary of the bug.
    validations:
      required: true

  - type: dropdown
    id: bug_location
    attributes:
      label: Bug Location 🗺️
      description: Specify where the bug is present.
      options:
        - Frontend
        - Backend
        - Both
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce 🔄
      description: Provide the steps to reproduce the bug.
      placeholder: List the steps needed to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior ✔️
      description: Describe what you expected to happen.
      placeholder: Describe the expected behavior.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior ❌
      description: Describe what actually happened.
      placeholder: Describe the actual behavior.
    validations:
      required: true

  - type: checkboxes
    id: bug_solution
    attributes:
      label: Proposed Solution
      description: How do you plan to fix the bug?
      options:
        - label: I will provide a pull request to fix this bug.
        - label: I need help to fix this bug.
    validations:
      required: true

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Adherence to Code of Conduct
      description: By submitting this issue, you agree to abide by our [CONTRIBUTING GUIDELINES.](../blob/master/CONTRIBUTING.md)
      options:
        - label: I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.
          required: true
